apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dialogflow-inbox
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dialogflow-inbox
            image: docker.pkg.github.com/mishushakov/dialogflow-inbox/dialogflow-inbox:latest
            imagePullPolicy: IfNotPresent
            env:
              # see README
          restartPolicy: Never